### ISSUE TITLE
Global Traffic map chart

### ISSUE THREAD

**Issue by dennismartensson** [epochjs/epoch#135]
Will the map like the one of "Global Traffic" on fastly.com be added to the libary?

**Comment by dennismartensson** [comment]
@rsandor How is your work going on the better way to display geospatial data?

**Comment by rsandor** [comment]
@dennismartensson - This is currently scrapped for the time being. Going to open up an enhancement ticket to look into this again in the future. Unfortunately most of my efforts in the coming weeks will be dedicated to handling repairs and removing accumulated technical debt in this long stagnant project.
