### ISSUE TITLE
Get the color being used for a layer

### ISSUE THREAD

**Issue by simonwistow** [epochjs/epoch#137]
When trying to make an external key for a chart it would be useful to be able to somehow get the color being used for a layer so that I can make the key the same color and have it change if I change theme.

**Comment by rsandor** [comment]
The colors are dictated by the CSS. Specifically you can find the color of a particular category by using the `div.ref.category1` through `div.ref.category20` classes inside a div with the class `.epoch`.

**Comment by rsandor** [comment]
Going to add a documentation issue that specifically addresses communicating this.

**Comment by MarcoSulla** [comment]
How can I change the color of a realtime grapf? I tried with realtime line and I find only a bad trick:

```
chart.getVisibleLayers()[0].className = "layer category2"
chart.redraw()
```
