### ISSUE TITLE
Please distribute unminified source code for debugging

### ISSUE THREAD

**Issue by toolness** [epochjs/epoch#154]
Because Epoch seems to lack a lot of documentation right now, I'm not entirely sure how to use it, and tracebacks from minified JS are utterly unhelpful in figuring that out. Please consider making an **unminified** version of `epoch.js` available for easy debugging!

**Comment by rsandor** [comment]
@toolness - Actually there is full documentation for the project. Run `cake documentation` and it will generate full html documentation in the `doc` directory. As far as non-minified source is concerned you can easily build this yourself by running `cake build` and then using the resulting `js/epoch.js`.

**Comment by jrmartin** [comment]
@rsandor Hello, I tried the approach you mentioned for creating the epoch.js, it created many js files for me (adapters.js, basics.js,  data, model, epoch, time) as well as folders of the same name with more js files. Are all files needed when creating the epoch.min.js?

**Comment by rsandor** [comment]
@jrmartin - The `js/epoch/` directory will contain each of the individual files, but the file `js/epoch.js` contains the fully concatenated javascript for the entire project. The individual files are created using `build` task and then they are packaged into a single javascript file via the `package` task. Finally, the `compile` task takes the single js file and runs it through the Google Closure Compiler.

Does this clarify things?

**Comment by rsandor** [comment]
I am also starting to lean towards having a non-minified version in the repository. Thinking about redoing the build system to use grunt or gulp. Anyone have opinions either way?

**Comment by jrmartin** [comment]
@rsandor  Thanks. I was able to compile using "cake build" from src, but I had to remove the "SASS" target from the "build" command in the CakeFile. It was getting stuck for me, and not executing the "package" target, which was why I wasn't able to see the final result of epoch.js. 

 It's an awesome library, haven't seen any other graphs that do it so smoothly.A non minified version would be useful, would make debugging easier when using the console. It would also make it easier for those us without much coffeescript knowledge to get it from github, although coffeescript ain't that hard.

**Comment by rsandor** [comment]
Hmm, must be an issue with the current node-sass package. I'll look into it
soon. Thanks for the heads up!

**Comment by toolness** [comment]
Ah, thanks!

I guess I just meant how libraries like jQuery [distribute](http://jquery.com/download/) both minified and unminified source, you know? It's very useful for developers who are just experimenting with a library to be able to poke into how it works without having to fork the project's github repository, install its build system prerequisites and generate its documentation and unminified source. That would have made my initial experience with your library a lot more pleasant.

That said, thanks for the help, I will definitely generate the docs and unminified version next time!

**Comment by rsandor** [comment]
This is now a pretty high priority. Also it seems having everything in coffeescript without a modern build system is causing a slew of maintainability issues. Going to file a new ticket to cleanup the build scripts.

**Comment by rsandor** [comment]
This is now done, you can find the fully un-minified compiled javascript in the repository at `dist/js/epoch.js`.
