### ISSUE TITLE
Multiaxes

### ISSUE THREAD

**Issue by gobwas** [epochjs/epoch#157]
Hello! 

Is it possible to use realtime graph with multiaxes?

I mean, something like that: http://www.flotcharts.org/flot/examples/axes-multiple/index.html

Thanks!

**Comment by rsandor** [comment]
@gobwas -  Currently Epoch doesn't support multi-axis support for real-time line charts. However, this might not be too hard to implement by extending the current real-time line chart. Let me take a look into this for you (and perhaps we can just make a new chart!).

**Comment by gobwas** [comment]
Thank you very much!

**Comment by rca** [comment]
This would be a very useful feature!  Thanks for getting this rolling again @rsandor !

**Comment by rsandor** [comment]
@gobwas & @rca - I started a PR that should address this issue for the real-time line plot. Please [have a look](https://github.com/epochjs/epoch/pull/198) and let me know what you think or if you have any suggestions. Cheers.

**Comment by gobwas** [comment]
@rsandor :fireworks: :beers:

**Comment by rsandor** [comment]
This is in epoch as of 0.8.0, documentation coming soon. If you want to start using it sooner see the PR: #198
