### ISSUE TITLE
Cannot run `cake build`

### ISSUE THREAD

**Issue by jme783** [epochjs/epoch#159]
I'm trying to run `cake build` to get an unminified version of the library for debugging purposes. It seems as the terminal hangs on `Compiling SCSS into CSS...` and sits idle. The job never finishes. Any ideas?

**Comment by jme783** [comment]
The SCSS task is not working correctly, removing it from the `Cakefile` allows the rest of the task to run.

**Comment by rsandor** [comment]
Noticed this myself tonight when I was testing some pull requests. Making this a very high priority.
