### ISSUE TITLE
tickFormat.right not working for time charts

### ISSUE THREAD

**Issue by woozyking** [epochjs/epoch#164]
`tickFormat.left` in this case works, however.

This is with __v0.6.0__

Snippet:

```
$('#some-id').epoch({
  type: 'time.line',
  axes: ['right', 'bottom'],
  data: data,
  tickFormats: {
    right: function(d) {
      return '$' + (d / 100000).toFixed(3);
    }
  }
});
```

**Comment by woozyking** [comment]
Also confirmed not working for `time.bar` and `time.area`

**Comment by jme783** [comment]
+1, also seeing that setting `ticks` is not working either

**Comment by rsandor** [comment]
I am not sure why that would be happening, anyone free to look into this?

**Comment by rsandor** [comment]
@woozyking - I just tried this locally on chrome and the `tickFormat.right` seems to work just fine for me. Here's a full example (file is located in the epoch root directory):

```html
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script> -->
  <script src="dist/js/epoch.js"></script>
  <link rel="stylesheet" type="text/css" href="dist/css/epoch.css">
</head>
<body>

  <div class="epoch" id="event-bar-chart" style="width: 500px; height: 150px"></div>

  <script>
  var chart = new Epoch.Time.Area({
    el: '#event-bar-chart',
    axes: ['right', 'bottom'],
    tickFormats: {
      right: function (d) {
        return '$' + (d / 100000).toFixed(3);
      }
    },
    data: [
      // First series
      {
        label: "Series 1",
        values: [{time: 1370044800, y: 1000000}, {time: 1370044801, y: 1000000}]
      },
      // The second series
      {
        label: "Series 2",
        values: [{time: 1370044800, y: 780000}, {time: 1370044801, y: 98000}]
      }
    ]
  });
  chart.draw();
  </script>
</body>
</html>
```

**Comment by woozyking** [comment]
I'll try this on the plane on Monday (didn't put it clearly in the other thread), and let you know when I arrive.



—
Runzhou Li (Leo)

**Comment by woozyking** [comment]
@rsandor I just tried it quickly before boarding and the issue seems to be around the jQuery plugin.

The modified usage:

```html
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/epoch/0.6.0/epoch.min.css">
</head>
<body>

  <div class="epoch" id="event-bar-chart" style="width: 500px; height: 150px"></div>

  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://cdn.jsdelivr.net/d3js/3.5.6/d3.min.js"></script>
  <script src="https://cdn.jsdelivr.net/epoch/0.6.0/epoch.min.js"></script>
  <script>
  var chart = $('#event-bar-chart').epoch({
    type: 'time.area',
    axes: ['right', 'bottom'],
    tickFormats: {
      right: function (d) {
        return '$' + (d / 100000).toFixed(3);
      }
    },
    data: [
      // First series
      {
        label: "Series 1",
        values: [{time: 1370044800, y: 1000000}, {time: 1370044801, y: 1000000}]
      },
      // The second series
      {
        label: "Series 2",
        values: [{time: 1370044800, y: 780000}, {time: 1370044801, y: 98000}]
      }
    ]
  });
  chart.draw();
  </script>
</body>
</html>
```

**Comment by woozyking** [comment]
Actually never mind. I just remember now what the problem is. The issue is that it's not formatting right axis as defined in `tickFormat.right` function.

**Comment by woozyking** [comment]
![test html](https://cloud.githubusercontent.com/assets/2837532/10281518/0476d84e-6b43-11e5-8ba6-27fabfd8d8ed.png)

This is what I got from the example, where the right axis labels are expected to have dollar sign in front

**Comment by rsandor** [comment]
<img width="171" alt="screen shot 2015-10-05 at 7 02 55 am" src="https://cloud.githubusercontent.com/assets/146592/10282346/2821bade-6b2f-11e5-91c7-4cb83429aa7a.png">
This is very strange as I am able to get the `$` to appear. What browser and version are you using to see these results?

**Comment by woozyking** [comment]
Latest stable Chrome on latest stable OS X.




I can only get the format working on basic charts.



—
Runzhou Li (Leo)

**Comment by rsandor** [comment]
Are you still using 0.6.0? Did you try the new release 0.7.1?

**Comment by woozyking** [comment]
Oh yea I’m still using 0.6.0. Let me try 0.7.1.

—
Runzhou Li (Leo)

**Comment by woozyking** [comment]
Just confirmed that 0.7.1 works as expected. I guess this can be closed. It'd be good to know though which exact commit fixed the issue.



—
Runzhou Li (Leo)

**Comment by rsandor** [comment]
I will leave that as an exercise for the reader ;), closing.
