### ISSUE TITLE
Realtime Charts dont work on IE

### ISSUE THREAD

**Issue by aanuprab** [epochjs/epoch#173]
IE 11 - Realtime Charts dont work. Getting 'getComputedStyle' error. Any fix?

Just open https://fastly.github.io/epoch/real-time and you will notice this error.

**Comment by aanuprab** [comment]
version 0.5.2 seems to be working fine. Looks like 0.6.0 has broken realtime charts on IE....too bad this is not maintained...

**Comment by woozyking** [comment]
Same as https://github.com/fastly/epoch/issues/161

**Comment by rsandor** [comment]
Is someone willing to debug this on IE11?

**Comment by rsandor** [comment]
Duplicate, as mentioned. Closing.
