### ISSUE TITLE
CDN url for the libraries?

### ISSUE THREAD

**Issue by ranguard** [epochjs/epoch#174]
Is there a CDN URL for the libraries, rather than having to serve them locally?

Just wondered if you knew anyone who could host it ;) ?

**Comment by jimaek** [comment]
You can always use http://www.jsdelivr.com/#!epoch
More info https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

**Comment by rsandor** [comment]
Yes I suggest using something like jsdelivr.com if you wish to have the files served via a CDN as opposed to locally. Closing this, and adding a quick ticket to update the README with that information.
