### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by chenminhua** [epochjs/epoch#180]
how can i make a chart to be responsive design?
if I don't set the width and height, the chart won't apper in my website.
please help me. thanks a lot

**Comment by amethyst82** [comment]
I didn't try this before
But I think set the container div's width & height with percentage value maybe could work

**Comment by rsandor** [comment]
Currently Epoch is not built to be automatically responsive. Better handling of this is noted for future versions of the library.

**Comment by eldiep** [comment]
Is it still scheduled to make epoch responsive? In my eyes this is absolutely essential nowadays.
