### ISSUE TITLE
Is Epoch Still Maintained?

### ISSUE THREAD

**Issue by woozyking** [epochjs/epoch#182]
This is a fantastic project with a good mix of ease of use and performance (for realtime graphing). Really hate to see this gets faded away.

**Comment by askmatey** [comment]
:+1:

**Comment by woozyking** [comment]
@askmatey I contacted the author himself, and unfortunately he can no long continue working on this project due to certain copyright and/or IP issue, since he left Fastly.

I'm trying to learn this and hopefully one day I can make a meaningful fork and develop for this project. In the meanwhile I'd encourage someone either make a fork and announce it here to indicate its purpose of continuing on the project development, or we can start a petition to ask Fastly to resolve the copyright issue with the original author @rsandor

**Comment by tyler** [comment]
Hey all. This was a misunderstanding and I apologize for how long it's taken to notice and resolve this. I'm in contact with @rsandor right now and we are working out how to resolve this and prevent it from happening again. 

We try to be good open source stewards and this was a failure. I'm sorry.

**Comment by woozyking** [comment]
:+1: Thank you @tyler !

**Comment by grodansparadis** [comment]
GREAT!

**Comment by aanuprab** [comment]
+1 I would like to contribute.

**Comment by tomasz-jomedia** [comment]
Any news regarding long term maintenance ?

**Comment by tyler** [comment]
We just transferred Epoch to github.com/epochjs/epoch. @rsandor has access again and all is well! :)

**Comment by woozyking** [comment]
That's really good to know! Thank you guys for the effort.



—
Runzhou Li (Leo)

**Comment by aanuprab** [comment]
Awesome. Thanks @tyler

**Comment by rsandor** [comment]
Hi all, so it has been a while since I was able to contribute to the library. I am going to be going through the tickets this weekend and figuring out what some of the higher priorities are for the library. Once the tickets have been categorized I'll post again with how you can help contribute. Thanks to everyone who helped make it possible to keep epoch going :+1:

**Comment by rsandor** [comment]
I managed to make it through all of the open PRs and Tickets. Everything has been categorized via labels (bug, enhancement, etc.). The next step is to come up with a "next steps" plan for the library as a whole. The latest feature code in the repository is ancient in JS terms (over a year), so this is a bit daunting.

Here are some clear areas where we need to focus to get the project back on its feet again:

1. **Build Scripts** - the current build scripts for the project are archaic and flat out broken. This is a good opportunity to recreate the way the project is built and packaged. Additionally we will want to include a fully un-minified version of the source for ease of debugging. **I plan on fixing these issues ASAP**

2. **Documentation** - the current gh-pages documentation is more of a marketing tool than it is a useful reference for the library. We need to put a lot of work into making sure it clearly communicates the library's capabilities, limitations, uses, compatibilities, and prerequisites. **Any help here would be greatly appreciated**.

3. **JavaScript vs CoffeeScript** - This is going to have to be settled sometime in the near future. Using CoffeeScript as the implementation language makes it harder for people to contribute. I will be looking into moving the entire library over to using JS very soon.

4. **Testing** - The current testing methodology needs revision. We need to investigate a way to make the project completely test automated (so it can be run on TravisCI or another tool). The rendering tests are very heavy weight and weird to code against. We also need to find a way to ensure rendering tests can be performed without the need to look at 15 HTML pages every time a change is made.

5. **Bugs** - There are a slew of bugs that have been reported over the last year or so. A lot of these bugs surround the real-time chart axes options (which do not seem to be working). Any help you can all provide with tracking these bugs down and fixing them would be very much appreciated.

This should get us all started on getting the project back up to snuff. If you want to contribute simply say so and I will help guide you to an issue that needs attention. Thanks!

**Comment by rsandor** [comment]
A quick note: I have completely redone the build scripts for the project and we are now using gulp. It is very small, clean, and easy-to-read in comparison to the Cakefile from before.

**Comment by rsandor** [comment]
Going to close this out as the project is back on track. Working on a future planning section that will incorporate the short-term goals listed above.
