### ISSUE TITLE
Update README: Public CDN URLs

### ISSUE THREAD

**Issue by rsandor** [epochjs/epoch#184]
As detailed in #174, add a quick entry to the readme to explain how to use jsdelivr.com to serve Epoch.

**Comment by srinath-v** [comment]
@rsandor Sent in a pull request with the addition.

**Comment by rsandor** [comment]
@srinath-v - When you made the PR you could have added `Fixes #184; ` in the title along with the description of the change. If done that way it will automatically close the associated ticket when the PR is merged :).

**Comment by srinath-v** [comment]
@rsandor Still quite new to all this. Will keep in mind.
