### ISSUE TITLE
Document Multi-Axis Support for Line Charts

### ISSUE THREAD

**Issue by rsandor** [epochjs/epoch#199]
Once Multi-Axis Support is merged document it for both the real-time and basic line plots.

**Comment by rsandor** [comment]
This is related to #198

**Comment by rsandor** [comment]
@rca - Do you want to take a stab at this? I just finished the thing and I am too tired to write documentation to the `gh-pages` branch :sleepy:

**Comment by rca** [comment]
Yes, I will take a look.

**Comment by rsandor** [comment]
@rca - Any word on this?

**Comment by rca** [comment]
Will do this today.

**Comment by rsandor** [comment]
Great let me know if you need an assist :)

**Comment by rca** [comment]
@rsandor please take a look at #205

**Comment by rsandor** [comment]
Nice, this is totes done. Thanks for your hard work :)
