### ISSUE TITLE
Is to possible to add text inside a gauge ?

### ISSUE THREAD

**Issue by tarun1188** [epochjs/epoch#206]
Hi,

Is it possible to add some text inside the gauge while creating it ? If not, can some one help me obtaining it using css. I have add a sample image which i created using paint.

![gauge](https://cloud.githubusercontent.com/assets/2683705/10518129/9975dd2c-737d-11e5-8728-2c278f9fe76e.jpg)

**Comment by rsandor** [comment]
It is possible to do this using Css tricks. Let me send you an example
tonight.

**Comment by rsandor** [comment]
Here is an example of how to do this with the "gauge-small" type chart:

```html
  <div id="gaugeChart" class="epoch gauge-small">
    <label>Text Here</label>
  </div>
  <script>
    $('#gaugeChart').epoch({
      type: 'time.gauge',
      value: 0.5
    });
  </script>
  <style>
    #gaugeChart label {
      display: block;
      text-align: center;
      position: relative;
      top: 125px;
    }
  </style>
```

Which results in this:
<img width="193" alt="screen shot 2015-10-17 at 4 36 26 am" src="https://cloud.githubusercontent.com/assets/146592/10558564/04780904-7489-11e5-84e3-e155bd183463.png">

The key here is the `top` attribute. For this I simply took the height of the `gauge-small` class (135px) and subtracted 10 to get the desired result.

Each size for the gauge has its own pre-defined height, for the exact size for each type see the [documentation](http://epochjs.github.io/epoch/real-time/#gauge) on the Epoch Github Pages site.
