### ISSUE TITLE
Top of the realtime line graph has been cut.

### ISSUE THREAD

**Issue by redbox-cdn** [epochjs/epoch#211]
The realtime Line graph sometimes not show the top of graph.

Here is the SS.
![ss](https://cloud.githubusercontent.com/assets/7666840/11521543/82a3b43c-98f0-11e5-8ef4-088efcc9ae32.png)

What should I modify the css or html..

My code is here.

```
<div id="test" class="epoch category20" style="width: 400px; height: 200px;"></div>

idx = ((new Date()).getTime()/1000)|0;
var request = [
  { label: 'Series 1', values: [ {time: idx, y: 0}] }
];

var request1 = $('#test').epoch({
    type: 'time.line',
    data: request,
    ticks: { time: 10, right: 6, left: 6 },                  
    fps: 30,
    margins: { top: 20, right: 70, bottom: 20, left: 70 },
    axes: ['right', 'bottom']
});
request = [{time: time, y: request}];
request1.push(request);
```

Thanks!

**Comment by rsandor** [comment]
Hm, this is strange. I will look into asap and get back to you. Cheers!

**Comment by redbox2000** [comment]
Hi thank you for quick reply.

I have add the sample code on jsfiddle

http://jsfiddle.net/vhsrqre0/3/

When you access the test site , the graph is displayed.

Test Site
https://http2.redbox.ne.jp/

Thanks!

**Comment by segphault** [comment]
Any word on this? I'm encountering a similar issue in my project. The lines at the top and bottom of the graph are thinner, as though partially truncated.

**Comment by rsandor** [comment]
@segphault - haven't had the chance to look at it. If it's causing a problem my bet would be it's the CSS cutting off the top. Mind looking into it?

**Comment by segphault** [comment]
yeah, I'll see what I can figure out. It doesn't appear to be a CSS issue, the line runs all the way to the edge of the canvas element and the behavior doesn't appear to change when I set margins. I'm going to experiment with the code that computes the canvas size and see if that sheds any light.

**Comment by rsandor** [comment]
Thanks so much!
